// Autogenerated test file: test7



import ContactPage from '../pages/contactPage';

describe('Add Contact Form', () => {
    let contactPage;

    beforeEach(() => {
        // Paso 1: Visitar la página de autenticación
        cy.visit('https://thinking-tester-contact-list.herokuapp.com/');

        // Paso 2: Realizar el proceso de autenticación (ajusta los selectores según sea necesario)
        cy.get('#email').type('enzocervi@gmail.com'); // Ingresa tu email de autenticación
        cy.get('#password').type('hola1234');      // Ingresa tu contraseña
        cy.get('button#submit').should('be.visible').click(); // Si el botón tiene un id de 'submit'        // Botón para iniciar sesión

        // Paso 3: Esperar a que la página de contacto se cargue
        cy.url().should('eq', 'https://thinking-tester-contact-list.herokuapp.com/contactList');
        
        // Paso 4: Hacer clic en el botón "Add Contact" para navegar al formulario
        cy.get('button#add-contact').should('be.visible').click();

        // Verificar que estamos en la página de "Add Contact"
        cy.url().should('eq', 'https://thinking-tester-contact-list.herokuapp.com/addContact');

        // Crear una instancia de la página del formulario de contacto
        contactPage = new ContactPage();
    });

    it('should successfully submit the form with all required fields filled in correctly', () => {
        const contactData = {
            firstName: 'Ignacio',
            lastName: 'Licciardi',
            birthdate: '1999-04-25',
            email: 'ignaciolicciardi@gmail.com',
            phone: '2615789632',
            street1: 'Av. San Martin 2577',
            street2: 'Colon 123',
            city: 'Mendoza',
            stateProvince: 'Mendoza',
            postalCode: 'asdf',
            country: 'Argentina'
        };

        // Llenar el formulario de contacto
        contactPage.fillContactForm(contactData);
        contactPage.submitForm();

        // Verificar que no haya errores al enviar el formulario
        cy.get('#error').should('not.exist');
    });
});


